import type { CategoryId } from "./categories";

export interface Spell {
  id: string;
  name: string;
  icon: string;
  categories: CategoryId[];
}

export interface ClassSpec {
  id: string;
  name: string;
  spells: Spell[];
}

export interface WowClass {
  id: string;
  name: string;
  color: string;
  shared: Spell[];
  specs: ClassSpec[];
}

const icon = (n: string) => n;

export const CLASSES: WowClass[] = [
  {
    id: "warrior",
    name: "Warrior",
    color: "#C69B6D",
    shared: [
      { id: "war_pummel",       name: "Pummel",              icon: icon("inv_gauntlets_04"),               categories: ["interrupt"] },
      { id: "war_shieldwall",   name: "Shield Wall",         icon: icon("ability_warrior_shieldwall"),     categories: ["defensive"] },
      { id: "war_rallying",     name: "Rallying Cry",        icon: icon("ability_warrior_rallyingcry"),    categories: ["raid_cd", "defensive"] },
      { id: "war_charge",       name: "Charge",              icon: icon("ability_warrior_charge"),         categories: ["gap_closer", "movement"] },
      { id: "war_heroicleap",   name: "Heroic Leap",         icon: icon("ability_heroicleap"),             categories: ["movement", "gap_closer"] },
      { id: "war_intimidating", name: "Intimidating Shout",  icon: icon("ability_golemthunderclap"),       categories: ["cc"] },
      { id: "war_stormbolt",    name: "Storm Bolt",          icon: icon("warrior_talent_icon_stormbolt"),  categories: ["stun"] },
      { id: "war_berserker",    name: "Berserker Rage",      icon: icon("spell_nature_ancestralguardian"), categories: ["utility_1"] },
      { id: "war_victoryrush",  name: "Impending Victory",   icon: icon("ability_warrior_devastate"),      categories: ["self_heal"] },
      { id: "war_slam",         name: "Slam",                icon: icon("ability_warrior_decisivestrike"), categories: ["builder"] },
      { id: "war_overpower",    name: "Overpower",           icon: icon("ability_meleedamage"),            categories: ["builder"] },
      { id: "war_whirlwind",    name: "Whirlwind",           icon: icon("ability_whirlwind"),              categories: ["aoe_dmg"] },
      { id: "war_victoryrush_pvp", name: "Disarm",           icon: icon("inv_sword_06"),                   categories: ["pvp_utility"] },
    ],
    specs: [
      { id: "arms", name: "Arms", spells: [
        { id: "war_avatar",     name: "Avatar",           icon: icon("warrior_talent_icon_avatar"),    categories: ["major_cd"] },
        { id: "war_bladestm",   name: "Bladestorm",       icon: icon("ability_warrior_bladestorm"),    categories: ["burst_cd", "aoe_dmg", "immunity"] },
        { id: "war_execute_a",  name: "Execute",          icon: icon("inv_sword_48"),                  categories: ["execute"] },
        { id: "war_dieby",      name: "Die by the Sword", icon: icon("ability_warrior_challange"),     categories: ["defensive"] },
        { id: "war_mortalstrike",name: "Mortal Strike",   icon: icon("ability_warrior_savageblow"),    categories: ["spender"] },
        { id: "war_colossus",   name: "Colossus Smash",   icon: icon("ability_warrior_colossussmash"), categories: ["burst_cd"] },
        { id: "war_skullsplit", name: "Skullsplitter",    icon: icon("inv_axe_66"),                    categories: ["builder"] },
        { id: "war_cleave",    name: "Cleave",            icon: icon("ability_warrior_cleave"),        categories: ["aoe_dmg"] },
        { id: "war_sweep",     name: "Sweeping Strikes",  icon: icon("ability_rogue_slicedice"),       categories: ["aoe_dmg"] },
        { id: "war_sharpenblade",name: "Sharpen Blade",   icon: icon("inv_sword_50"),                   categories: ["pvp_offensive"] },
        { id: "war_duel",       name: "Duel",             icon: icon("ability_warrior_weaponmastery"),  categories: ["pvp_offensive"] },
      ]},
      { id: "fury", name: "Fury", spells: [
        { id: "war_recklessness", name: "Recklessness",   icon: icon("warrior_talent_icon_innerrage"), categories: ["major_cd"] },
        { id: "war_enraged",      name: "Enraged Regen",   icon: icon("ability_warrior_focusedrage"),  categories: ["self_heal", "defensive"] },
        { id: "war_execute_f",    name: "Execute",         icon: icon("inv_sword_48"),                  categories: ["execute"] },
        { id: "war_bloodthirst",  name: "Bloodthirst",    icon: icon("spell_nature_bloodlust"),       categories: ["self_heal", "builder"] },
        { id: "war_ragingblow",   name: "Raging Blow",    icon: icon("ability_warrior_ragingblow"),    categories: ["spender"] },
        { id: "war_rampage",     name: "Rampage",          icon: icon("ability_warrior_rampage"),       categories: ["spender"] },
        { id: "war_dragonsroar", name: "Dragon's Roar",    icon: icon("ability_warrior_dragonsroar"),   categories: ["aoe_dmg"] },
        { id: "war_odynsfury",   name: "Odyn's Fury",     icon: icon("ability_warrior_odynsguardian"), categories: ["aoe_dmg"] },
        { id: "war_siegebreaker",name: "Siegebreaker",    icon: icon("ability_warrior_shieldbreak"),   categories: ["burst_cd"] },
        { id: "war_wreckingball",name: "Wrecking Ball",   icon: icon("ability_warrior_wreckingball"), categories: ["pvp_offensive"] },
      ]},
      { id: "protection", name: "Protection", spells: [
        { id: "war_lastsstand",   name: "Last Stand",        icon: icon("spell_holy_ashestoashes"),    categories: ["defensive"] },
        { id: "war_avatar_p",    name: "Avatar",            icon: icon("warrior_talent_icon_avatar"), categories: ["major_cd"] },
        { id: "war_shieldblock", name: "Shield Block",      icon: icon("ability_defend"),             categories: ["defensive"] },
        { id: "war_spellreflect",name: "Spell Reflection",  icon: icon("ability_warrior_shieldreflection"), categories: ["immunity", "defensive"] },
        { id: "war_shieldslam",  name: "Shield Slam",       icon: icon("ability_warrior_shieldbash"), categories: ["spender"] },
        { id: "war_revenge",     name: "Revenge",           icon: icon("ability_warrior_revenge"),    categories: ["builder"] },
        { id: "war_thunderclap", name: "Thunder Clap",      icon: icon("spell_nature_thunderclap"),   categories: ["aoe_dmg"] },
        { id: "war_ignorepain",  name: "Ignore Pain",       icon: icon("ability_warrior_ignorepain"), categories: ["defensive"] },
        { id: "war_demoralizing",name: "Demoralizing Shout",icon: icon("ability_warrior_warcry"),     categories: ["defensive"] },
      ]},
    ],
  },
  {
    id: "paladin",
    name: "Paladin",
    color: "#F58CBA",
    shared: [
      { id: "pal_rebuke",     name: "Rebuke",              icon: icon("spell_holy_rebuke"),                categories: ["interrupt"] },
      { id: "pal_bop",        name: "Blessing of Protection", icon: icon("spell_holy_sealofprotection"),    categories: ["immunity", "defensive"] },
      { id: "pal_divshield",  name: "Divine Shield",       icon: icon("spell_holy_divineshield"),          categories: ["immunity"] },
      { id: "pal_lay",        name: "Lay on Hands",        icon: icon("spell_holy_layonhands"),            categories: ["self_heal", "raid_cd"] },
      { id: "pal_steed",      name: "Divine Steed",        icon: icon("ability_paladin_divinesteed"),      categories: ["movement"] },
      { id: "pal_hammer",     name: "Hammer of Justice",   icon: icon("spell_holy_sealofmight"),           categories: ["stun"] },
      { id: "pal_repent",     name: "Repentance",          icon: icon("spell_holy_prayerofhealing02"),     categories: ["cc"] },
      { id: "pal_cleanse",    name: "Cleanse Toxins",      icon: icon("spell_holy_renew"),                 categories: ["dispel"] },
      { id: "pal_freedom",    name: "Blessing of Freedom", icon: icon("spell_holy_sealofvalor"),          categories: ["utility_1"] },
      { id: "pal_sac",        name: "Blessing of Sacrifice", icon: icon("spell_holy_sealofsacrifice"),    categories: ["raid_cd"] },
      { id: "pal_judgment",   name: "Judgment",            icon: icon("spell_holy_righteousfury"),         categories: ["builder"] },
      { id: "pal_consecrate", name: "Consecration",        icon: icon("spell_holy_innerfire"),            categories: ["aoe_dmg"] },
      { id: "pal_blindinglight",name: "Blinding Light",    icon: icon("ability_paladin_blindinglight"),   categories: ["pvp_utility"] },
    ],
    specs: [
      { id: "holy", name: "Holy", spells: [
        { id: "pal_avenging_h", name: "Avenging Wrath", icon: icon("spell_holy_avenginewrath"), categories: ["major_cd"] },
        { id: "pal_aura_mast",  name: "Aura Mastery",   icon: icon("spell_holy_auramastery"),   categories: ["raid_cd"] },
        { id: "pal_dispel_h",   name: "Cleanse",        icon: icon("spell_holy_renew"),         categories: ["dispel"] },
        { id: "pal_holyshock",  name: "Holy Shock",     icon: icon("spell_holy_holyshock"),     categories: ["builder"] },
        { id: "pal_lightofmartyr",name:"Light of the Martyr",icon: icon("ability_paladin_lightofthemartyr"), categories: ["spender"] },
      ]},
      { id: "protection", name: "Protection", spells: [
        { id: "pal_ardent",      name: "Ardent Defender",           icon: icon("spell_holy_ardentdefender"), categories: ["defensive"] },
        { id: "pal_guardian",    name: "Guardian of Ancient Kings",  icon: icon("spell_holy_heroism"),       categories: ["defensive"] },
        { id: "pal_avengshield", name: "Avenger's Shield",          icon: icon("spell_holy_avengersshield"),categories: ["gap_closer", "interrupt"] },
        { id: "pal_shieldofright",name: "Shield of the Righteous",   icon: icon("ability_paladin_shieldofvengeance"), categories: ["spender"] },
        { id: "pal_consecrate_p",name: "Consecration",              icon: icon("spell_holy_innerfire"),     categories: ["aoe_dmg"] },
        { id: "pal_bulwark",    name: "Bulwark of Order",            icon: icon("spell_holy_blessingofprotection"), categories: ["pvp_defensive"] },
      ]},
      { id: "retribution", name: "Retribution", spells: [
        { id: "pal_wings_r",    name: "Avenging Wrath",       icon: icon("spell_holy_avenginewrath"),  categories: ["major_cd"] },
        { id: "pal_shield_r",   name: "Shield of Vengeance",  icon: icon("ability_paladin_shieldofthetemplar"), categories: ["defensive"] },
        { id: "pal_execution",  name: "Execution Sentence",   icon: icon("spell_paladin_executionsentence"),    categories: ["burst_cd"] },
        { id: "pal_templar",    name: "Templar's Verdict",    icon: icon("spell_paladin_templarsverdict"),      categories: ["spender"] },
        { id: "pal_crusader",   name: "Crusader Strike",      icon: icon("spell_holy_crusaderstrike"),          categories: ["builder"] },
        { id: "pal_bladeofjustice",name: "Blade of Justice",  icon: icon("ability_paladin_bladeofjustice"),     categories: ["builder"] },
        { id: "pal_divinetempest",name: "Divine Tempest",     icon: icon("ability_paladin_divinetempest"),      categories: ["aoe_dmg"] },
        { id: "pal_finalreckoning",name: "Final Reckoning",  icon: icon("ability_paladin_finalreckoning"),     categories: ["burst_cd"] },
        { id: "pal_lawbringer", name: "Lawbringer",           icon: icon("spell_holy_sealofcommand"),           categories: ["pvp_offensive"] },
      ]},
    ],
  },
  {
    id: "hunter",
    name: "Hunter",
    color: "#AAD372",
    shared: [
      { id: "hun_counter",    name: "Counter Shot",           icon: icon("ability_hunter_aspectoftheviper"), categories: ["interrupt"] },
      { id: "hun_turtle",     name: "Aspect of the Turtle",   icon: icon("ability_hunter_pet_turtle"),       categories: ["immunity"] },
      { id: "hun_exhilar",    name: "Exhilaration",           icon: icon("ability_hunter_onewithnature"),    categories: ["self_heal"] },
      { id: "hun_cheetah",    name: "Aspect of the Cheetah",  icon: icon("ability_mount_jungletiger"),      categories: ["movement"] },
      { id: "hun_disengage",  name: "Disengage",              icon: icon("ability_rogue_feint"),             categories: ["movement"] },
      { id: "hun_freezing",   name: "Freezing Trap",          icon: icon("spell_frost_chainsofice"),        categories: ["cc"] },
      { id: "hun_intim",      name: "Intimidation",           icon: icon("ability_devour"),                categories: ["stun"] },
      { id: "hun_tranq",      name: "Tranquilizing Shot",     icon: icon("ability_hunter_aimedshot"),       categories: ["purge"] },
      { id: "hun_misd",       name: "Misdirection",           icon: icon("ability_hunter_misdirection"),     categories: ["utility_1"] },
      { id: "hun_killshot",   name: "Kill Shot",              icon: icon("ability_hunter_killshot"),         categories: ["execute"] },
      { id: "hun_multishot",  name: "Multi-Shot",             icon: icon("ability_hunter_multishot"),        categories: ["aoe_dmg"] },
      { id: "hun_tartrap",    name: "Tar Trap",               icon: icon("spell_nature_slowdown"),          categories: ["pvp_utility"] },
    ],
    specs: [
      { id: "beast_mastery", name: "Beast Mastery", spells: [
        { id: "hun_bestial",   name: "Bestial Wrath",     icon: icon("ability_druid_ferociousbite"),  categories: ["major_cd"] },
        { id: "hun_acherd",    name: "Aspect of the Wild",icon: icon("spell_nature_protectionformnature"), categories: ["burst_cd"] },
        { id: "hun_killcommand",name: "Kill Command",     icon: icon("ability_hunter_killcommand"),    categories: ["spender"] },
        { id: "hun_barbedshot",name: "Barbed Shot",       icon: icon("ability_hunter_barbedshot"),     categories: ["builder"] },
        { id: "hun_cobra",    name: "Cobra Shot",          icon: icon("ability_hunter_cobrashot"),      categories: ["spender"] },
        { id: "hun_killclaw", name: "Kill Cleave",        icon: icon("ability_hunter_killcleave"),     categories: ["aoe_dmg"] },
        { id: "hun_chimera",  name: "Chimaera Shot",      icon: icon("ability_hunter_chimerashot"),    categories: ["spender"] },
        { id: "hun_bloodspatter",name: "Bloodspatter",    icon: icon("ability_hunter_survivalinstincts"), categories: ["pvp_offensive"] },
      ]},
      { id: "marksmanship", name: "Marksmanship", spells: [
        { id: "hun_trueshot",  name: "Trueshot",           icon: icon("ability_trueshot"),             categories: ["major_cd"] },
        { id: "hun_volley",    name: "Volley",              icon: icon("ability_hunter_rapidkilling"),  categories: ["aoe_dmg"] },
        { id: "hun_aimedshot", name: "Aimed Shot",         icon: icon("inv_spear_07"),                  categories: ["spender"] },
        { id: "hun_steadyshot",name: "Steady Shot",        icon: icon("ability_hunter_steadyshot"),     categories: ["builder"] },
        { id: "hun_arcane",    name: "Arcane Shot",         icon: icon("ability_hunter_arcane_shot"),    categories: ["builder"] },
        { id: "hun_rapidfire", name: "Rapid Fire",          icon: icon("ability_hunter_rapidfire"),     categories: ["spender"] },
        { id: "hun_explosive", name: "Explosive Shot",      icon: icon("ability_hunter_explosiveshot"), categories: ["aoe_dmg"] },
        { id: "hun_doubletap", name: "Double Tap",          icon: icon("ability_hunter_doubletap"),     categories: ["burst_cd"] },
        { id: "hun_ranger",   name: "Ranger's Finesse",     icon: icon("ability_hunter_camoflauge"),    categories: ["pvp_offensive"] },
      ]},
      { id: "survival", name: "Survival", spells: [
        { id: "hun_coordi",    name: "Coordinated Assault",icon: icon("inv_ability_hunter_coordinatedassault"), categories: ["major_cd"] },
        { id: "hun_wing",      name: "Wing Clip",          icon: icon("ability_rogue_trip"),            categories: ["utility_2"] },
        { id: "hun_raptor",   name: "Raptor Strike",       icon: icon("ability_hunter_raptorstrike"),   categories: ["builder"] },
        { id: "hun_mongoose", name: "Mongoose Bite",       icon: icon("ability_hunter_mongoosebite"),   categories: ["spender"] },
        { id: "hun_flanking", name: "Flanking Strike",      icon: icon("ability_hunter_flankingstrike"), categories: ["builder"] },
        { id: "hun_butchery", name: "Butchery",             icon: icon("ability_hunter_butchery"),       categories: ["aoe_dmg"] },
        { id: "hun_carve",    name: "Carve",                icon: icon("ability_hunter_carve"),          categories: ["aoe_dmg"] },
        { id: "hun_spear",    name: "Spear of Bastion",     icon: icon("ability_hunter_spearofbastion"), categories: ["burst_cd"] },
        { id: "hun_muzzle_pvp",name: "Muzzle",             icon: icon("ability_hunter_muzzle"),         categories: ["pvp_utility"] },
      ]},
    ],
  },
  {
    id: "mage",
    name: "Mage",
    color: "#3FC7EB",
    shared: [
      { id: "mage_counter",    name: "Counterspell",    icon: icon("spell_frost_iceshock"),            categories: ["interrupt"] },
      { id: "mage_iceblock",   name: "Ice Block",       icon: icon("spell_frost_frost"),               categories: ["immunity"] },
      { id: "mage_blink",      name: "Blink",           icon: icon("spell_arcane_blink"),              categories: ["movement"] },
      { id: "mage_polymorph",  name: "Polymorph",       icon: icon("spell_nature_polymorph"),          categories: ["cc"] },
      { id: "mage_invis",      name: "Invisibility",    icon: icon("ability_mage_invisibility"),       categories: ["utility_1", "defensive"] },
      { id: "mage_spellsteal", name: "Spellsteal",      icon: icon("spell_arcane_arcane02"),           categories: ["purge"] },
      { id: "mage_remove",     name: "Remove Curse",    icon: icon("spell_nature_removecurse"),        categories: ["dispel"] },
      { id: "mage_barrier",    name: "Mass Barrier",    icon: icon("spell_arcane_prismaticcloak"),     categories: ["raid_cd"] },
      { id: "mage_alter",      name: "Alter Time",      icon: icon("spell_mage_altertime"),            categories: ["defensive", "self_heal"] },
      { id: "mage_arcaneexplosion",name: "Arcane Explosion",icon: icon("spell_nature_novablast"),      categories: ["aoe_dmg"] },
      { id: "mage_frostbolt",  name: "Frostbolt",        icon: icon("spell_frost_frostbolt"),           categories: ["builder"] },
      { id: "mage_greaterinvis",name: "Greater Invisibility",icon: icon("ability_mage_greaterinvisibility"), categories: ["pvp_defensive"] },
    ],
    specs: [
      { id: "arcane", name: "Arcane", spells: [
        { id: "mage_arcsurge",  name: "Arcane Surge",       icon: icon("spell_nature_wispsplode"),         categories: ["major_cd"] },
        { id: "mage_evocation", name: "Evocation",          icon: icon("spell_nature_purge"),              categories: ["self_heal"] },
        { id: "mage_touchm",   name: "Touch of the Magi",  icon: icon("spell_arcane_arcane01"),           categories: ["burst_cd"] },
        { id: "mage_arcanemissiles",name: "Arcane Missiles",icon: icon("spell_nature_starfall"),          categories: ["spender"] },
        { id: "mage_arcanebarrage",name: "Arcane Barrage", icon: icon("spell_arcane_arcanebarrage"),       categories: ["spender"] },
        { id: "mage_arcaneblast",name: "Arcane Blast",     icon: icon("spell_arcane_arcaneblast"),         categories: ["spender"] },
        { id: "mage_arcanefamiliar",name: "Arcane Familiar",icon: icon("spell_arcane_arcane_familiar"),  categories: ["builder"] },
        { id: "mage_netherwind",name: "Netherwind Armor",  icon: icon("spell_arcane_netherwind"),          categories: ["pvp_defensive"] },
      ]},
      { id: "fire", name: "Fire", spells: [
        { id: "mage_combust",   name: "Combustion",        icon: icon("spell_fire_sealoffire"),           categories: ["major_cd"] },
        { id: "mage_dragon",    name: "Dragon's Breath",   icon: icon("inv_misc_head_dragon_01"),          categories: ["cc"] },
        { id: "mage_pyro",      name: "Pyroblast",         icon: icon("spell_fire_fireball02"),           categories: ["spender"] },
        { id: "mage_fireball",  name: "Fireball",          icon: icon("spell_fire_fireball"),             categories: ["builder"] },
        { id: "mage_fireblast", name: "Fire Blast",         icon: icon("spell_fire_fireball"),             categories: ["builder"] },
        { id: "mage_phoenix",   name: "Phoenix Flames",    icon: icon("spell_fire_phoenixflames"),        categories: ["aoe_dmg"] },
        { id: "mage_livingbomb",name: "Living Bomb",       icon: icon("spell_fire_livingbomb"),           categories: ["aoe_dmg", "dot"] },
        { id: "mage_meteor",    name: "Meteor",            icon: icon("spell_fire_meteor"),               categories: ["burst_cd"] },
        { id: "mage_scorch",    name: "Scorch",            icon: icon("spell_fire_scorch"),               categories: ["builder"] },
        { id: "mage_kleptomania",name: "Kleptomania",      icon: icon("spell_arcane_arcane02"),           categories: ["pvp_offensive"] },
      ]},
      { id: "frost", name: "Frost", spells: [
        { id: "mage_icyveins",  name: "Icy Veins",         icon: icon("spell_frost_coldhearted"),         categories: ["major_cd"] },
        { id: "mage_frostnova", name: "Frost Nova",         icon: icon("spell_frost_frostnova"),           categories: ["stun"] },
        { id: "mage_coldsnap",  name: "Cold Snap",         icon: icon("spell_frost_wizardmark"),          categories: ["self_heal"] },
        { id: "mage_ice lance", name: "Ice Lance",         icon: icon("spell_frost_icelance"),            categories: ["spender"] },
        { id: "mage_flurry",    name: "Flurry",             icon: icon("spell_frost_flurry"),              categories: ["builder"] },
        { id: "mage_frozenorb", name: "Frozen Orb",        icon: icon("spell_frost_frozenorb"),           categories: ["aoe_dmg"] },
        { id: "mage_glacialspike",name: "Glacial Spike",   icon: icon("spell_frost_glacialspike"),        categories: ["spender"] },
        { id: "mage_rayoffrost",name: "Ray of Frost",      icon: icon("spell_frost_rayoffrost"),          categories: ["spender"] },
        { id: "mage_cone",      name: "Cone of Cold",       icon: icon("spell_frost_glacier"),             categories: ["aoe_dmg"] },
        { id: "mage_ringoffrost",name: "Ring of Frost",    icon: icon("spell_frost_ringoffrost"),         categories: ["cc"] },
        { id: "mage_iceform",   name: "Ice Form",           icon: icon("spell_frost_frostarmor"),          categories: ["pvp_defensive"] },
      ]},
    ],
  },
  {
    id: "priest",
    name: "Priest",
    color: "#FFFFFF",
    shared: [
      { id: "pri_silence",   name: "Silence",            icon: icon("ability_priest_silence"),          categories: ["interrupt"] },
      { id: "pri_disperse",  name: "Dispersion",         icon: icon("spell_shadow_dispersion"),         categories: ["defensive", "immunity"] },
      { id: "pri_pws",       name: "Power Word: Shield", icon: icon("spell_holy_powerwordshield"),     categories: ["defensive"] },
      { id: "pri_fade",      name: "Fade",               icon: icon("spell_magic_lesserinvisibilty"),  categories: ["movement", "utility_1"] },
      { id: "pri_psyscream", name: "Psychic Scream",     icon: icon("spell_shadow_psychicscream"),      categories: ["cc"] },
      { id: "pri_masdispel", name: "Mass Dispel",         icon: icon("spell_arcane_massdispel"),        categories: ["dispel", "purge"] },
      { id: "pri_lifeswap",  name: "Leap of Faith",      icon: icon("priest_spell_leapoffaith_a"),     categories: ["utility_2"] },
      { id: "pri_vampemb",   name: "Vampiric Embrace",    icon: icon("spell_shadow_unsummonbuilding"),  categories: ["self_heal", "raid_cd"] },
      { id: "pri_smite",     name: "Smite",               icon: icon("spell_holy_holysmite"),           categories: ["builder"] },
      { id: "pri_mindblast", name: "Mind Blast",          icon: icon("spell_shadow_unholyfrenzy"),      categories: ["builder"] },
      { id: "pri_mindspike", name: "Mind Spike",          icon: icon("spell_shadow_shadowwordpain"),    categories: ["builder"] },
      { id: "pri_dominantmind",name: "Dominant Mind",     icon: icon("spell_shadow_domination"),        categories: ["pvp_utility"] },
    ],
    specs: [
      { id: "discipline", name: "Discipline", spells: [
        { id: "pri_painsup",   name: "Pain Suppression", icon: icon("spell_holy_painsupression"),   categories: ["defensive", "raid_cd"] },
        { id: "pri_rapture",   name: "Rapture",          icon: icon("spell_holy_rapture"),          categories: ["major_cd"] },
        { id: "pri_powerinf",  name: "Power Infusion",   icon: icon("spell_holy_powerinfusion"),    categories: ["major_cd"] },
        { id: "pri_penance",   name: "Penance",          icon: icon("spell_holy_penance"),          categories: ["spender"] },
        { id: "pri_solace",    name: "Power Word: Solace",icon: icon("spell_holy_blindinglight2"),  categories: ["builder"] },
        { id: "pri_schism",    name: "Schism",           icon: icon("spell_holy_felrayschism"),     categories: ["burst_cd"] },
        { id: "pri_radiance",  name: "Power Word: Radiance",icon: icon("spell_holy_powerwordradiance"), categories: ["spender"] },
      ]},
      { id: "holy", name: "Holy", spells: [
        { id: "pri_guardian",  name: "Guardian Spirit",  icon: icon("spell_holy_guardianspirit"),   categories: ["defensive", "raid_cd"] },
        { id: "pri_divhymn",   name: "Divine Hymn",       icon: icon("spell_holy_divinehymn"),       categories: ["raid_cd"] },
        { id: "pri_apotheosis",name: "Apotheosis",        icon: icon("ability_priest_ascension"),    categories: ["major_cd"] },
        { id: "pri_holyfire",  name: "Holy Fire",         icon: icon("spell_holy_holyfire"),         categories: ["builder"] },
        { id: "pri_holyword_s",name: "Holy Word: Serenity",icon: icon("spell_holy_holywordserenity"),categories: ["spender"] },
        { id: "pri_holyword_s2",name: "Holy Word: Sanctify",icon: icon("spell_holy_holywordsanctify"),categories: ["aoe_dmg"] },
        { id: "pri_lightweaver",name: "Lightweaver",      icon: icon("spell_holy_symbolofhope"),     categories: ["pvp_defensive"] },
      ]},
      { id: "shadow", name: "Shadow", spells: [
        { id: "pri_voidform",   name: "Voidform",          icon: icon("spell_priest_voidform"),       categories: ["major_cd"] },
        { id: "pri_shadowfiend",name: "Shadowfiend",       icon: icon("spell_shadow_shadowfiend"),    categories: ["burst_cd"] },
        { id: "pri_devour",     name: "Devouring Plague",  icon: icon("spell_shadow_devouringplague"),categories: ["spender"] },
        { id: "pri_vampirictouch",name: "Vampiric Touch",  icon: icon("spell_shadow_vampirictouch"), categories: ["dot"] },
        { id: "pri_shadowwordpain",name: "Shadow Word: Pain",icon: icon("spell_shadow_shadowwordpain"),categories: ["dot"] },
        { id: "pri_mindflay",  name: "Mind Flay",          icon: icon("spell_shadow_siphonmana"),     categories: ["builder"] },
        { id: "pri_mindbender",name: "Mindbender",         icon: icon("spell_shadow_shadowfiend"),    categories: ["burst_cd"] },
        { id: "pri_voidbolt",  name: "Void Bolt",          icon: icon("spell_shadow_voidbolt"),       categories: ["spender"] },
        { id: "pri_silenceshadow",name: "Silence",         icon: icon("ability_priest_silence"),      categories: ["interrupt"] },
        { id: "pri_psychiclink",name: "Psychic Link",      icon: icon("spell_shadow_psychicscream"),  categories: ["pvp_offensive"] },
      ]},
    ],
  },
  {
    id: "rogue",
    name: "Rogue",
    color: "#FFF468",
    shared: [
      { id: "rog_kick",      name: "Kick",              icon: icon("ability_kick"),                    categories: ["interrupt"] },
      { id: "rog_cloak",     name: "Cloak of Shadows",   icon: icon("spell_shadow_nethercloak"),        categories: ["immunity"] },
      { id: "rog_vanish",    name: "Vanish",             icon: icon("ability_vanish"),                  categories: ["immunity", "movement"] },
      { id: "rog_evasion",   name: "Evasion",            icon: icon("spell_shadow_shadowward"),         categories: ["defensive"] },
      { id: "rog_feint",     name: "Feint",              icon: icon("ability_rogue_feint"),             categories: ["defensive"] },
      { id: "rog_sprint",    name: "Sprint",             icon: icon("ability_rogue_sprint"),            categories: ["movement"] },
      { id: "rog_grappling", name: "Grappling Hook",     icon: icon("ability_rogue_grapplinghook"),     categories: ["gap_closer", "movement"] },
      { id: "rog_kidney",    name: "Kidney Shot",        icon: icon("ability_rogue_kidneyshot"),        categories: ["stun"] },
      { id: "rog_sap",       name: "Sap",                icon: icon("ability_sap"),                     categories: ["cc"] },
      { id: "rog_blind",     name: "Blind",              icon: icon("spell_shadow_mindsteal"),          categories: ["cc"] },
      { id: "rog_shiv",      name: "Shiv",               icon: icon("inv_throwingknife_06"),            categories: ["purge"] },
      { id: "rog_crimson",   name: "Crimson Vial",       icon: icon("inv_alchemy_elixir_05"),           categories: ["self_heal"] },
      { id: "rog_cheapshot", name: "Cheap Shot",         icon: icon("ability_rogue_cheapshot"),         categories: ["stun"] },
      { id: "rog_blind_pvp", name: "Smoke Bomb",         icon: icon("ability_rogue_smokebomb"),         categories: ["pvp_defensive"] },
    ],
    specs: [
      { id: "assassination", name: "Assassination", spells: [
        { id: "rog_deathmark", name: "Deathmark",         icon: icon("inv_ability_assassinationrogue_deathmark"), categories: ["major_cd"] },
        { id: "rog_mutilate", name: "Mutilate",           icon: icon("ability_rogue_mutilate"),        categories: ["builder"] },
        { id: "rog_envenom",  name: "Envenom",            icon: icon("ability_rogue_envenom"),         categories: ["spender"] },
        { id: "rog_rupture",  name: "Rupture",            icon: icon("ability_rogue_rupture"),         categories: ["dot"] },
      { id: "rog_garrote",   name: "Garrote",             icon: icon("ability_rogue_garrote"),         categories: ["dot"] },
        { id: "rog_fanofknives",name: "Fan of Knives",    icon: icon("ability_rogue_fanofknives"),     categories: ["aoe_dmg"] },
        { id: "rog_crimsontempest",name: "Crimson Tempest",icon: icon("ability_rogue_crimsontempest"), categories: ["aoe_dmg"] },
        { id: "rog_kingsbane",name: "Kingsbane",          icon: icon("inv_dagger_09"),                  categories: ["burst_cd"] },
        { id: "rog_poisonbomb",name: "Poison Bomb",       icon: icon("inv_misc_herb_04"),               categories: ["pvp_offensive"] },
      ]},
      { id: "outlaw", name: "Outlaw", spells: [
        { id: "rog_adrenaline",name: "Adrenaline Rush",   icon: icon("spell_shadow_shadowworddominate"),categories: ["major_cd"] },
        { id: "rog_bladeflur", name: "Blade Flurry",      icon: icon("ability_rogue_bladeflurry"),     categories: ["aoe_dmg"] },
        { id: "rog_sinister", name: "Sinister Strike",    icon: icon("ability_rogue_swordcombat"),     categories: ["builder"] },
        { id: "rog_dispatch", name: "Dispatch",           icon: icon("ability_rogue_dispatch"),        categories: ["spender"] },
        { id: "rog_betweentheeyes",name: "Between the Eyes",icon: icon("ability_rogue_between_the_eyes"),categories: ["stun", "spender"] },
        { id: "rog_rollthebones",name: "Roll the Bones",  icon: icon("ability_rogue_rollthebones"),    categories: ["burst_cd"] },
        { id: "rog_killing spree",name: "Killing Spree",  icon: icon("ability_rogue_murderspree"),     categories: ["burst_cd"] },
        { id: "rog_ghostly",  name: "Ghostly Strike",     icon: icon("ability_rogue_ghostlystrike"),   categories: ["pvp_offensive"] },
      ]},
      { id: "subtlety", name: "Subtlety", spells: [
        { id: "rog_shadowdance",name: "Shadow Dance",     icon: icon("ability_rogue_shadowdance"),     categories: ["burst_cd"] },
        { id: "rog_shadowblades",name: "Shadow Blades",  icon: icon("inv_knife_1h_grimbatolraid_d_03"),categories: ["major_cd"] },
        { id: "rog_shadowstrike",name: "Shadowstrike",   icon: icon("ability_rogue_shadowstrike"),    categories: ["builder"] },
        { id: "rog_eviscerate",name: "Eviscerate",       icon: icon("ability_rogue_eviscerate"),      categories: ["spender"] },
        { id: "rog_backstab",  name: "Backstab",          icon: icon("ability_backstab"),              categories: ["builder"] },
        { id: "rog_symbols",   name: "Symbols of Death",  icon: icon("ability_rogue_symbolsofdeath"), categories: ["burst_cd"] },
        { id: "rog_secret",    name: "Secret Technique",  icon: icon("ability_rogue_secrettechnique"), categories: ["spender"] },
        { id: "rog_shurikenstorm",name: "Shuriken Storm",icon: icon("ability_rogue_shurikenstorm"),  categories: ["aoe_dmg"] },
        { id: "rog_shurikentoss",name: "Shuriken Toss",   icon: icon("ability_rogue_shurikentoss"),   categories: ["pvp_offensive"] },
        { id: "rog_shadowyduel",name: "Shadowy Duel",    icon: icon("ability_rogue_shadowyduel"),     categories: ["pvp_utility"] },
      ]},
    ],
  },
  {
    id: "shaman",
    name: "Shaman",
    color: "#0070DE",
    shared: [
      { id: "sha_windshear",  name: "Wind Shear",       icon: icon("spell_nature_cyclone"),            categories: ["interrupt"] },
      { id: "sha_astralshift",name: "Astral Shift",     icon: icon("spell_shaman_astralshift"),        categories: ["defensive"] },
      { id: "sha_ghostwolf",  name: "Ghost Wolf",       icon: icon("spell_nature_spiritwolf"),         categories: ["movement"] },
      { id: "sha_hex",        name: "Hex",              icon: icon("spell_shaman_hex"),                categories: ["cc"] },
      { id: "sha_purge",      name: "Purge",            icon: icon("spell_nature_purge"),              categories: ["purge"] },
      { id: "sha_tremor",     name: "Tremor Totem",     icon: icon("spell_nature_tremortotem"),        categories: ["utility_1"] },
      { id: "sha_capacitor",  name: "Capacitor Totem",  icon: icon("spell_nature_brilliance"),         categories: ["stun"] },
      { id: "sha_grounding",  name: "Grounding Totem",  icon: icon("spell_nature_groundingtotem"),     categories: ["utility_2"] },
      { id: "sha_blooldust",  name: "Bloodlust",        icon: icon("spell_nature_bloodlust"),          categories: ["major_cd", "raid_cd"] },
      { id: "sha_flameshock", name: "Flame Shock",      icon: icon("spell_fire_flameshock"),           categories: ["dot"] },
      { id: "sha_frostshock", name: "Frost Shock",      icon: icon("spell_frost_frostshock"),          categories: ["builder"] },
      { id: "sha_earthshock", name: "Earth Shock",      icon: icon("spell_nature_earthshock"),         categories: ["spender"] },
      { id: "sha_purgespirit",name: "Purge Spirit",     icon: icon("spell_nature_purge"),              categories: ["pvp_utility"] },
    ],
    specs: [
      { id: "elemental", name: "Elemental", spells: [
        { id: "sha_stormkeep",  name: "Stormkeeper",     icon: icon("ability_thunderking_lightningwhip"),categories: ["burst_cd"] },
        { id: "sha_firelem",   name: "Fire Elemental",  icon: icon("spell_fire_elemental_totem"),      categories: ["major_cd"] },
        { id: "sha_earthshield",name: "Earth Shield",   icon: icon("spell_nature_skinofearth"),        categories: ["self_heal"] },
        { id: "sha_lavaburst", name: "Lava Burst",      icon: icon("spell_shaman_lavaburst"),          categories: ["spender"] },
        { id: "sha_lightningbolt",name: "Lightning Bolt",icon: icon("spell_nature_lightning"),         categories: ["builder"] },
        { id: "sha_chainlightning",name: "Chain Lightning",icon: icon("spell_nature_chainlightning"),  categories: ["aoe_dmg"] },
        { id: "sha_earthquake", name: "Earthquake",      icon: icon("spell_nature_earthquake"),         categories: ["aoe_dmg"] },
        { id: "sha_elementalblast",name: "Elemental Blast",icon: icon("spell_shaman_elementalblast"), categories: ["burst_cd"] },
        { id: "sha_liquidmagma",name: "Liquid Magma Totem",icon: icon("spell_shaman_liquidmagma"),    categories: ["pvp_offensive"] },
      ]},
      { id: "enhancement", name: "Enhancement", spells: [
        { id: "sha_feralspirit",name: "Feral Spirit",    icon: icon("spell_shaman_feralspirit"),        categories: ["major_cd"] },
        { id: "sha_doomwinds", name: "Doom Winds",       icon: icon("ability_ironmaidens_swirl"),       categories: ["burst_cd"] },
        { id: "sha_healsurge", name: "Healing Surge",   icon: icon("spell_nature_healingway"),         categories: ["self_heal"] },
        { id: "sha_stormstrike",name: "Stormstrike",    icon: icon("ability_shaman_stormstrike"),      categories: ["spender"] },
        { id: "sha_windstrike",name: "Windstrike",      icon: icon("ability_shaman_windstrike"),       categories: ["spender"] },
        { id: "sha_lash",      name: "Lava Lash",       icon: icon("ability_shaman_lavalash"),         categories: ["spender"] },
        { id: "sha_crashlightning",name: "Crash Lightning",icon: icon("spell_shaman_crashlightning"),  categories: ["aoe_dmg"] },
        { id: "sha_sundering", name: "Sundering",        icon: icon("spell_shaman_sundering"),          categories: ["stun"] },
        { id: "sha_windsong",  name: "Windsong",         icon: icon("spell_shaman_windsong"),           categories: ["pvp_offensive"] },
      ]},
      { id: "restoration", name: "Restoration", spells: [
        { id: "sha_tide",      name: "Spirit Link Totem",icon: icon("spell_shaman_spiritlink"),      categories: ["raid_cd"] },
        { id: "sha_ascend",    name: "Ascendance",       icon: icon("spell_fire_elementaldevastation"),categories: ["major_cd"] },
        { id: "sha_purify",    name: "Purify Spirit",    icon: icon("spell_nature_giftofthewaterspirit"),categories: ["dispel"] },
        { id: "sha_riptide",   name: "Riptide",          icon: icon("spell_shaman_riptide"),           categories: ["builder"] },
        { id: "sha_healingrain",name: "Healing Rain",    icon: icon("spell_nature_healingrain"),       categories: ["aoe_dmg"] },
        { id: "sha_healingtide",name: "Healing Tide Totem",icon: icon("spell_shaman_healingtide"),    categories: ["raid_cd"] },
        { id: "sha_swelling",  name: "Swelling Rain",   icon: icon("spell_nature_healingrain"),       categories: ["pvp_defensive"] },
      ]},
    ],
  },
  {
    id: "warlock",
    name: "Warlock",
    color: "#8788EE",
    shared: [
      { id: "lock_spelllock",  name: "Spell Lock",              icon: icon("spell_shadow_mindrot"),            categories: ["interrupt"] },
      { id: "lock_unending",   name: "Unending Resolve",        icon: icon("spell_shadow_demonictactics"),     categories: ["defensive"] },
      { id: "lock_circle",     name: "Demonic Circle: Teleport",icon: icon("spell_shadow_demoniccirclesummon"),categories: ["movement"] },
      { id: "lock_burning",    name: "Burning Rush",            icon: icon("ability_deathwing_sealarmorbreachtga"), categories: ["movement"] },
      { id: "lock_fear",       name: "Fear",                    icon: icon("spell_shadow_possession"),         categories: ["cc"] },
      { id: "lock_banish",     name: "Banish",                  icon: icon("spell_shadow_cripple"),            categories: ["cc"] },
      { id: "lock_healthstone",name: "Healthstone",             icon: icon("inv_stone_04"),                    categories: ["self_heal"] },
      { id: "lock_curse",      name: "Curse of Tongues",        icon: icon("spell_shadow_curseoftounges"),    categories: ["utility_1"] },
      { id: "lock_dispel",     name: "Singe Magic (Imp)",       icon: icon("spell_fire_flameshock"),          categories: ["dispel"] },
      { id: "lock_axetoss",    name: "Axe Toss (Felguard)",    icon: icon("ability_warrior_titansgrip"),     categories: ["stun"] },
      { id: "lock_corruption", name: "Corruption",              icon: icon("spell_shadow_corruption"),         categories: ["dot"] },
      { id: "lock_shadowfury", name: "Shadowfury",              icon: icon("spell_shadow_shadowfury"),         categories: ["stun"] },
      { id: "lock_netherward", name: "Nether Ward",             icon: icon("spell_shadow_netherprotection"),   categories: ["pvp_defensive"] },
    ],
    specs: [
      { id: "affliction", name: "Affliction", spells: [
        { id: "lock_dark_a",  name: "Dark Soul: Misery",       icon: icon("spell_warlock_soulburn"),       categories: ["major_cd"] },
        { id: "lock_haunt",   name: "Haunt",                    icon: icon("ability_warlock_haunt"),        categories: ["burst_cd"] },
        { id: "lock_agony",   name: "Agony",                    icon: icon("spell_shadow_agony"),           categories: ["dot"] },
        { id: "lock_unstableaffliction",name: "Unstable Affliction",icon: icon("spell_shadow_unstableaffliction"), categories: ["dot"] },
        { id: "lock_siphonlife",name: "Siphon Life",           icon: icon("spell_shadow_siphonlife"),      categories: ["dot"] },
        { id: "lock_maleficrapture",name: "Malefic Rapture",   icon: icon("spell_shadow_maleficrapture"),  categories: ["spender"] },
        { id: "lock_drainsoul",name: "Drain Soul",              icon: icon("spell_shadow_haunting"),        categories: ["spender"] },
        { id: "lock_seedofcorruption",name: "Seed of Corruption",icon: icon("spell_shadow_seedofcorruption"),categories: ["aoe_dmg"] },
        { id: "lock_soulrot", name: "Soul Rot",                 icon: icon("spell_shadow_soulrot"),         categories: ["pvp_offensive"] },
      ]},
      { id: "demonology", name: "Demonology", spells: [
        { id: "lock_tyrant",  name: "Summon Demonic Tyrant",   icon: icon("inv_summondemonictyrant"),  categories: ["major_cd"] },
        { id: "lock_imps",    name: "Implosion",               icon: icon("spell_fel_implosion"),      categories: ["aoe_dmg"] },
        { id: "lock_demonbolt",name: "Demonbolt",              icon: icon("spell_warlock_demonbolt"),   categories: ["spender"] },
        { id: "lock_shadowbolt_d",name: "Shadow Bolt",         icon: icon("spell_shadow_shadowbolt"),   categories: ["builder"] },
        { id: "lock_handofguldan",name: "Hand of Gul'dan",     icon: icon("spell_shadow_handofguldan"), categories: ["spender"] },
        { id: "lock_call_dreadstalkers",name: "Call Dreadstalkers",icon: icon("spell_shadow_summonfelhunter"), categories: ["burst_cd"] },
        { id: "lock_vilefiend",name: "Summon Vilefiend",       icon: icon("spell_warlock_summonvilefiend"), categories: ["burst_cd"] },
        { id: "lock_netherportal",name: "Nether Portal",       icon: icon("spell_shadow_netherportal"), categories: ["pvp_offensive"] },
      ]},
      { id: "destruction", name: "Destruction", spells: [
        { id: "lock_havoc",       name: "Havoc",              icon: icon("ability_warlock_baneofhavoc"),  categories: ["burst_cd"] },
        { id: "lock_chaos",       name: "Summon Infernal",    icon: icon("spell_shadow_summoninfernal"),  categories: ["major_cd"] },
        { id: "lock_shadowburn",  name: "Shadowburn",         icon: icon("spell_shadow_scourgebuild"),    categories: ["execute"] },
        { id: "lock_chaosbolt",   name: "Chaos Bolt",         icon: icon("spell_fire_bluepyroblast"),    categories: ["spender"] },
        { id: "lock_incinerate",  name: "Incinerate",         icon: icon("spell_fire_fire"),              categories: ["builder"] },
        { id: "lock_conflagrate", name: "Conflagrate",        icon: icon("spell_fire_fireball"),          categories: ["builder"] },
        { id: "lock_rainoffire",  name: "Rain of Fire",       icon: icon("spell_shadow_rainoffire"),     categories: ["aoe_dmg"] },
        { id: "lock_cataclysm",   name: "Cataclysm",          icon: icon("spell_fire_cataclysm"),        categories: ["aoe_dmg"] },
        { id: "lock_channel_demonfire",name: "Channel Demonfire",icon: icon("spell_fire_channeldemonfire"),categories: ["spender"] },
        { id: "lock_burningspell",name: "Burning Rush",       icon: icon("ability_deathwing_sealarmorbreachtga"), categories: ["pvp_offensive"] },
      ]},
    ],
  },
  {
    id: "deathknight",
    name: "Death Knight",
    color: "#C41E3A",
    shared: [
      { id: "dk_mindfreeze", name: "Mind Freeze",       icon: icon("spell_deathknight_mindfreeze"),    categories: ["interrupt"] },
      { id: "dk_amz",        name: "Anti-Magic Zone",   icon: icon("spell_deathknight_antimagiczone"), categories: ["raid_cd"] },
      { id: "dk_ams",        name: "Anti-Magic Shell",  icon: icon("spell_shadow_antimagicshell"),     categories: ["immunity", "defensive"] },
      { id: "dk_icebound",   name: "Icebound Fortitude",icon: icon("spell_deathknight_iceboundfortitude"), categories: ["defensive"] },
      { id: "dk_deathgrip",  name: "Death Grip",        icon: icon("spell_deathknight_strangulate"),   categories: ["gap_closer", "utility_1"] },
      { id: "dk_chains",     name: "Chains of Ice",     icon: icon("spell_frost_chainsofice"),         categories: ["utility_2"] },
      { id: "dk_asphyxiate", name: "Asphyxiate",        icon: icon("ability_deathknight_asphixiate"),  categories: ["stun"] },
      { id: "dk_deathstrike",name: "Death Strike",      icon: icon("spell_deathknight_butcher2"),      categories: ["self_heal"] },
      { id: "dk_wraithwalk", name: "Wraith Walk",       icon: icon("ability_deathknight_wraithwalk"),  categories: ["movement"] },
      { id: "dk_deathcoil",  name: "Death Coil",        icon: icon("spell_shadow_deathcoil"),          categories: ["spender"] },
      { id: "dk_outbreak",   name: "Outbreak",          icon: icon("spell_deathknight_outbreak"),      categories: ["dot"] },
      { id: "dk_deathgrip_pvp",name: "Necrotic Strike", icon: icon("spell_deathknight_necroticstrike"),categories: ["pvp_offensive"] },
    ],
    specs: [
      { id: "blood", name: "Blood", spells: [
        { id: "dk_vampblood",  name: "Vampiric Blood",        icon: icon("spell_shadow_lifedrain"),          categories: ["defensive"] },
        { id: "dk_dancingrw", name: "Dancing Rune Weapon",    icon: icon("inv_sword_07"),                     categories: ["major_cd"] },
        { id: "dk_marrowrend",name: "Marrowrend",             icon: icon("ability_deathknight_marrowrend"),   categories: ["builder"] },
        { id: "dk_heartstrike",name: "Heart Strike",           icon: icon("ability_deathknight_heartstrike"), categories: ["builder"] },
        { id: "dk_bloodboil",  name: "Blood Boil",            icon: icon("spell_deathknight_bloodboil"),      categories: ["aoe_dmg"] },
        { id: "dk_deathanddecay",name: "Death and Decay",     icon: icon("spell_shadow_deathanddecay"),       categories: ["aoe_dmg"] },
        { id: "dk_bonestorm", name: "Bonestorm",               icon: icon("ability_deathknight_bonestorm"),    categories: ["aoe_dmg"] },
        { id: "dk_tombstone", name: "Tombstone",              icon: icon("ability_deathknight_tombstone"),     categories: ["pvp_defensive"] },
      ]},
      { id: "frost", name: "Frost", spells: [
        { id: "dk_pillar",    name: "Pillar of Frost",         icon: icon("ability_deathknight_pillaroffrost"),categories: ["major_cd"] },
        { id: "dk_breath",    name: "Breath of Sindragosa",    icon: icon("spell_deathknight_breathofsindragosa"), categories: ["burst_cd"] },
        { id: "dk_obliterate",name: "Obliterate",             icon: icon("ability_deathknight_obliterate"),  categories: ["spender"] },
        { id: "dk_froststrike",name: "Frost Strike",          icon: icon("ability_deathknight_froststrike"), categories: ["spender"] },
        { id: "dk_howlingblast",name: "Howling Blast",        icon: icon("spell_frost_arcticwinds"),         categories: ["aoe_dmg"] },
        { id: "dk_frostscythe",name: "Frostscythe",           icon: icon("ability_deathknight_frostscythe"), categories: ["aoe_dmg"] },
        { id: "dk_reaper",    name: "Reaper's Mark",           icon: icon("ability_deathknight_reapersmark"), categories: ["burst_cd"] },
        { id: "dk_remorseless",name: "Remorseless Winter",    icon: icon("ability_deathknight_remorselesswinter"), categories: ["aoe_dmg"] },
        { id: "dk_chillstreak",name: "Chill Streak",          icon: icon("spell_frost_iceclod"),             categories: ["pvp_offensive"] },
      ]},
      { id: "unholy", name: "Unholy", spells: [
        { id: "dk_apoc",      name: "Apocalypse",              icon: icon("artifactability_unholydeathknight_deathsembrace"), categories: ["burst_cd"] },
        { id: "dk_unholy_a",  name: "Unholy Assault",          icon: icon("spell_deathvsdeath"),               categories: ["major_cd"] },
        { id: "dk_scourge",   name: "Scourge Strike",         icon: icon("spell_deathknight_scourgestrike"),  categories: ["spender"] },
        { id: "dk_festering", name: "Festering Strike",        icon: icon("spell_deathknight_festeringstrike"),categories: ["builder"] },
        { id: "dk_virulentplague",name: "Virulent Plague",     icon: icon("spell_deathknight_virulentplague"), categories: ["dot"] },
        { id: "dk_deathcoil_u",name: "Death Coil",            icon: icon("spell_shadow_deathcoil"),           categories: ["spender"] },
        { id: "dk_army",      name: "Army of the Dead",        icon: icon("spell_deathknight_armyofthedead"),  categories: ["major_cd"] },
        { id: "dk_soulreaper",name: "Soul Reaper",             icon: icon("spell_deathknight_soulreaper"),      categories: ["execute"] },
        { id: "dk_defile",    name: "Defile",                  icon: icon("spell_deathknight_defile"),         categories: ["aoe_dmg"] },
        { id: "dk_vilecontagion",name: "Vile Contagion",       icon: icon("spell_deathknight_vilecontagion"),  categories: ["pvp_offensive"] },
      ]},
    ],
  },
  {
    id: "monk",
    name: "Monk",
    color: "#00FF98",
    shared: [
      { id: "monk_sck",       name: "Spear Hand Strike", icon: icon("ability_monk_spearhand"),        categories: ["interrupt"] },
      { id: "monk_diffuse",   name: "Diffuse Magic",    icon: icon("spell_monk_diffusemagic"),         categories: ["defensive"] },
      { id: "monk_dampen",    name: "Dampen Harm",      icon: icon("ability_monk_dampenharm"),         categories: ["defensive"] },
      { id: "monk_touchok",   name: "Touch of Karma",   icon: icon("ability_monk_touchofkarma"),       categories: ["defensive"] },
      { id: "monk_roll",      name: "Roll",             icon: icon("ability_monk_roll"),               categories: ["movement"] },
      { id: "monk_tigerlust", name: "Tiger's Lust",     icon: icon("ability_monk_tigerslust"),         categories: ["movement", "utility_1"] },
      { id: "monk_paralysis", name: "Paralysis",        icon: icon("ability_monk_paralysis"),          categories: ["cc"] },
      { id: "monk_legsweep",  name: "Leg Sweep",        icon: icon("ability_monk_legsweep"),           categories: ["stun"] },
      { id: "monk_detox",     name: "Detox",            icon: icon("ability_rogue_imrovedrecuperate"), categories: ["dispel"] },
      { id: "monk_vivify",    name: "Vivify",           icon: icon("ability_monk_vivify"),             categories: ["self_heal"] },
      { id: "monk_tigerpalm", name: "Tiger Palm",       icon: icon("ability_monk_tigerpalm"),         categories: ["builder"] },
      { id: "monk_risingkick",name: "Rising Sun Kick",  icon: icon("ability_monk_risingsunkick"),      categories: ["spender"] },
      { id: "monk_grapple",   name: "Grapple Weapon",   icon: icon("ability_monk_grappleweapon"),      categories: ["pvp_utility"] },
    ],
    specs: [
      { id: "brewmaster", name: "Brewmaster", spells: [
        { id: "monk_purifyb",   name: "Purifying Brew",   icon: icon("ability_monk_quipinghand"),        categories: ["defensive"] },
        { id: "monk_celestbrew",name: "Celestial Brew",   icon: icon("ability_monk_ironskinbrew"),       categories: ["defensive"] },
        { id: "monk_kegsmash",  name: "Keg Smash",        icon: icon("ability_monk_kegsmash"),           categories: ["aoe_dmg"] },
        { id: "monk_breathoffire",name: "Breath of Fire", icon: icon("ability_monk_breathoffire"),       categories: ["aoe_dmg"] },
        { id: "monk_blackoutkick_b",name: "Blackout Kick",icon: icon("ability_monk_blackoutkick"),       categories: ["builder"] },
        { id: "monk_expelharm", name: "Expel Harm",       icon: icon("ability_monk_expelharm"),          categories: ["self_heal"] },
        { id: "monk_niuzao",    name: "Invoke Niuzao",    icon: icon("ability_monk_summonoxstatue"),      categories: ["major_cd"] },
        { id: "monk_fortifying",name: "Fortifying Brew", icon: icon("ability_monk_fortifyingale"),       categories: ["defensive"] },
      ]},
      { id: "mistweaver", name: "Mistweaver", spells: [
        { id: "monk_revival",  name: "Revival",           icon: icon("spell_monk_revival"),              categories: ["raid_cd"] },
        { id: "monk_lifecoc",  name: "Life Cocoon",      icon: icon("ability_monk_chicocoon"),          categories: ["raid_cd"] },
        { id: "monk_renewingmist",name: "Renewing Mist", icon: icon("ability_monk_renewingmist"),       categories: ["builder"] },
        { id: "monk_envelopingmist",name: "Enveloping Mist",icon: icon("spell_monk_envelopingmist"),  categories: ["spender"] },
        { id: "monk_essencefont",name: "Essence Font",   icon: icon("ability_monk_essencefont"),        categories: ["aoe_dmg"] },
        { id: "monk_chij",     name: "Invoke Chi-Ji",    icon: icon("ability_monk_summoncraneseraph"),  categories: ["major_cd"] },
        { id: "monk_songofchi",name: "Song of Chi-Ji",   icon: icon("ability_monk_songofchiji"),        categories: ["pvp_utility"] },
      ]},
      { id: "windwalker", name: "Windwalker", spells: [
        { id: "monk_storm",    name: "Storm, Earth, and Fire", icon: icon("spell_nature_giftofthewild"), categories: ["major_cd"] },
        { id: "monk_xuen",    name: "Invoke Xuen",       icon: icon("ability_monk_summontigerstatue"),  categories: ["major_cd"] },
        { id: "monk_serenity", name: "Serenity",          icon: icon("ability_monk_serenity"),           categories: ["burst_cd"] },
        { id: "monk_fistoffury",name: "Fists of Fury",   icon: icon("ability_monk_fistoffury"),        categories: ["spender"] },
        { id: "monk_blackoutkick",name: "Blackout Kick", icon: icon("ability_monk_blackoutkick"),       categories: ["builder"] },
        { id: "monk_spinningcrane",name: "Spinning Crane Kick",icon: icon("ability_monk_spinningcrane"),categories: ["aoe_dmg"] },
        { id: "monk_fistofwhitened",name: "Fist of the White Tiger",icon: icon("ability_monk_fistofwhitetiger"), categories: ["builder"] },
        { id: "monk_touchdeath",name: "Touch of Death",  icon: icon("ability_monk_touchofdeath"),       categories: ["execute"] },
        { id: "monk_jadestrike",name: "Jade Strike",     icon: icon("ability_monk_jadestrike"),         categories: ["pvp_offensive"] },
      ]},
    ],
  },
  {
    id: "druid",
    name: "Druid",
    color: "#FF7C0A",
    shared: [
      { id: "dru_skullbash",       name: "Skull Bash",          icon: icon("ability_druid_skullbash"),         categories: ["interrupt"] },
      { id: "dru_solarbeam",      name: "Solar Beam",         icon: icon("ability_vehicle_sonicshockwave"),  categories: ["interrupt"] },
      { id: "dru_barkskin",        name: "Barkskin",            icon: icon("spell_nature_stoneclawtotem"),     categories: ["defensive"] },
      { id: "dru_dash",            name: "Dash",                icon: icon("ability_druid_dash"),              categories: ["movement"] },
      { id: "dru_stampedingroar", name: "Stampeding Roar",    icon: icon("spell_druid_stampedingroar_cat"),categories: ["raid_cd", "movement"] },
      { id: "dru_cyclone",         name: "Cyclone",            icon: icon("spell_nature_earthbind"),          categories: ["cc"] },
      { id: "dru_hibernate",       name: "Hibernate",          icon: icon("spell_nature_sleep"),              categories: ["cc"] },
      { id: "dru_remcorr",         name: "Remove Corruption",  icon: icon("spell_holy_removecurse"),         categories: ["dispel"] },
      { id: "dru_innervate",       name: "Innervate",          icon: icon("spell_nature_lightning"),          categories: ["utility_1"] },
      { id: "dru_renewal",         name: "Renewal",            icon: icon("spell_nature_natureblessing"),     categories: ["self_heal"] },
      { id: "dru_moonfire",        name: "Moonfire",           icon: icon("spell_nature_starfall"),           categories: ["dot"] },
      { id: "dru_sunfire",         name: "Sunfire",            icon: icon("spell_nature_sunfire"),            categories: ["dot"] },
      { id: "dru_entanglingroots", name: "Entangling Roots",  icon: icon("spell_nature_stranglevines"),      categories: ["cc"] },
      { id: "dru_massentanglement",name: "Mass Entanglement",  icon: icon("spell_nature_massentanglement"),  categories: ["pvp_utility"] },
    ],
    specs: [
      { id: "balance", name: "Balance", spells: [
        { id: "dru_celestial",name: "Celestial Alignment",icon: icon("spell_nature_natureguardian"),   categories: ["major_cd"] },
        { id: "dru_starfall", name: "Starfall",           icon: icon("ability_druid_starfall"),          categories: ["aoe_dmg"] },
        { id: "dru_starsurge",name: "Starsurge",         icon: icon("spell_nature_starsurge"),          categories: ["spender"] },
        { id: "dru_starfire",name: "Starfire",            icon: icon("spell_arcane_starfire"),            categories: ["builder"] },
        { id: "dru_wrath",   name: "Wrath",               icon: icon("spell_nature_abolishmagic"),       categories: ["builder"] },
        { id: "dru_fullmoon",name: "Full Moon",           icon: icon("spell_nature_fullmoon"),           categories: ["burst_cd"] },
        { id: "dru_furyofelune",name: "Fury of Elune",   icon: icon("spell_nature_furyofelune"),        categories: ["burst_cd"] },
        { id: "dru_starlord",name: "Starlord",            icon: icon("spell_nature_starlord"),           categories: ["pvp_offensive"] },
      ]},
      { id: "feral", name: "Feral", spells: [
        { id: "dru_berserk_f",name: "Berserk",            icon: icon("ability_druid_berserk"),           categories: ["major_cd"] },
        { id: "dru_tigerfury",name: "Tiger's Fury",       icon: icon("ability_mount_jungletiger"),       categories: ["burst_cd"] },
        { id: "dru_rip",      name: "Rip",                icon: icon("ability_rogue_rip"),               categories: ["dot"] },
        { id: "dru_rake",     name: "Rake",               icon: icon("ability_druid_rake"),              categories: ["dot"] },
        { id: "dru_ferociousbite",name: "Ferocious Bite",icon: icon("ability_druid_ferociousbite"),     categories: ["spender"] },
        { id: "dru_shred",    name: "Shred",              icon: icon("ability_druid_shred"),             categories: ["builder"] },
        { id: "dru_thrash",   name: "Thrash",             icon: icon("ability_druid_thrash"),            categories: ["aoe_dmg"] },
        { id: "dru_brutalslash",name: "Brutal Slash",     icon: icon("ability_druid_brutalslash"),       categories: ["aoe_dmg"] },
        { id: "dru_maim",     name: "Maim",               icon: icon("ability_druid_maim"),              categories: ["stun"] },
        { id: "dru_savage",   name: "Savage Roar",        icon: icon("ability_druid_savagery"),          categories: ["pvp_offensive"] },
      ]},
      { id: "guardian", name: "Guardian", spells: [
        { id: "dru_survival_g",name: "Survival Instincts",icon: icon("ability_druid_tigersroar"),     categories: ["defensive"] },
        { id: "dru_frenzied",  name: "Frenzied Regeneration",icon: icon("ability_bullrush"),          categories: ["self_heal"] },
        { id: "dru_mangle",    name: "Mangle",             icon: icon("ability_druid_mangle"),            categories: ["builder"] },
        { id: "dru_thrash_g",  name: "Thrash",            icon: icon("ability_druid_thrash"),            categories: ["aoe_dmg"] },
        { id: "dru_ironfur",   name: "Ironfur",           icon: icon("ability_druid_ironfur"),           categories: ["defensive"] },
        { id: "dru_bristlingfur",name: "Bristling Fur",   icon: icon("ability_druid_bristlingfur"),     categories: ["defensive"] },
        { id: "dru_lunarbeam", name: "Lunar Beam",        icon: icon("spell_nature_fullmoon"),           categories: ["pvp_offensive"] },
      ]},
      { id: "restoration", name: "Restoration", spells: [
        { id: "dru_tranq",      name: "Tranquility",              icon: icon("spell_nature_tranquility"),        categories: ["raid_cd"] },
        { id: "dru_treeoflife", name: "Incarnation: Tree of Life",icon: icon("ability_druid_improvedtreeform"), categories: ["major_cd"] },
        { id: "dru_rejuvenation",name: "Rejuvenation",            icon: icon("spell_nature_rejuvenation"),      categories: ["builder"] },
        { id: "dru_wildgrowth", name: "Wild Growth",             icon: icon("ability_druid_wildgrowth"),        categories: ["spender"] },
        { id: "dru_swiftmend",  name: "Swiftmend",               icon: icon("spell_nature_resistnature"),       categories: ["spender"] },
        { id: "dru_efflorescence",name: "Efflorescence",          icon: icon("ability_druid_efflorescence"),    categories: ["aoe_dmg"] },
        { id: "dru_overgrowth", name: "Overgrowth",              icon: icon("spell_nature_overgrowth"),         categories: ["pvp_defensive"] },
      ]},
    ],
  },
  {
    id: "demonhunter",
    name: "Demon Hunter",
    color: "#A330C9",
    shared: [
      { id: "dh_disrupt",    name: "Disrupt",          icon: icon("ability_demonhunter_consumemagic"),categories: ["interrupt"] },
      { id: "dh_blur",       name: "Blur",             icon: icon("ability_demonhunter_blur"),        categories: ["defensive"] },
      { id: "dh_netherwalk", name: "Netherwalk",       icon: icon("spell_warlock_demonsoul"),         categories: ["immunity"] },
      { id: "dh_darkness",   name: "Darkness",         icon: icon("ability_demonhunter_darkness"),    categories: ["raid_cd"] },
      { id: "dh_meta",       name: "Metamorphosis",    icon: icon("ability_demonhunter_metamorphasisdps"), categories: ["major_cd"] },
      { id: "dh_vengrt",     name: "Vengeful Retreat", icon: icon("ability_demonhunter_vengefulretreat2"), categories: ["movement"] },
      { id: "dh_felrush",    name: "Fel Rush",         icon: icon("ability_demonhunter_felrush"),     categories: ["movement", "gap_closer"] },
      { id: "dh_imprison",   name: "Imprison",         icon: icon("ability_demonhunter_imprison"),    categories: ["cc"] },
      { id: "dh_chaosnova",  name: "Chaos Nova",       icon: icon("spell_fire_felfirenova"),          categories: ["stun"] },
      { id: "dh_consume",    name: "Consume Magic",    icon: icon("ability_demonhunter_consumemagic"),categories: ["purge"] },
      { id: "dh_throwglaive",name: "Throw Glaive",     icon: icon("ability_demonhunter_throwglaive"), categories: ["builder"] },
      { id: "dh_nemesis",    name: "Nemesis",          icon: icon("ability_demonhunter_nemesis"),     categories: ["pvp_offensive"] },
    ],
    specs: [
      { id: "havoc", name: "Havoc", spells: [
        { id: "dh_eyebeam",   name: "Eye Beam",          icon: icon("ability_demonhunter_eyebeam"),     categories: ["burst_cd", "aoe_dmg"] },
        { id: "dh_essence",   name: "Essence Break",     icon: icon("inv_glaive_1h_demonhunter_a_01"), categories: ["burst_cd"] },
        { id: "dh_annihilation",name: "Annihilation",   icon: icon("ability_demonhunter_annihilation"),categories: ["spender"] },
        { id: "dh_chaosstrike",name: "Chaos Strike",    icon: icon("ability_demonhunter_chaosstrike"), categories: ["spender"] },
        { id: "dh_demonsbite",name: "Demon's Bite",     icon: icon("ability_demonhunter_demonsbite"),  categories: ["builder"] },
        { id: "dh_bladedance",name: "Blade Dance",      icon: icon("ability_demonhunter_bladedance"),  categories: ["aoe_dmg"] },
        { id: "dh_deathsweep",name: "Death Sweep",      icon: icon("ability_demonhunter_deathsweep"), categories: ["aoe_dmg"] },
        { id: "dh_glaivetoss",name: "Glaive Toss",      icon: icon("ability_demonhunter_glaivetoss"),  categories: ["pvp_offensive"] },
        { id: "dh_unboundchaos",name: "Unbound Chaos",  icon: icon("ability_demonhunter_unboundchaos"),categories: ["pvp_offensive"] },
      ]},
      { id: "vengeance", name: "Vengeance", spells: [
        { id: "dh_metavenge", name: "Metamorphosis (Tank)",icon: icon("ability_demonhunter_metamorphasistank"),categories: ["defensive"] },
        { id: "dh_demspikes", name: "Demon Spikes",       icon: icon("ability_demonhunter_demonspikes"), categories: ["defensive"] },
        { id: "dh_soulcleave",name: "Soul Cleave",        icon: icon("ability_demonhunter_soulcleave"), categories: ["self_heal"] },
        { id: "dh_immolationaura",name: "Immolation Aura",icon: icon("ability_demonhunter_immolationaura"),categories: ["aoe_dmg"] },
        { id: "dh_fracture",  name: "Fracture",           icon: icon("ability_demonhunter_fracture"),   categories: ["builder"] },
        { id: "dh_shear",     name: "Shear",              icon: icon("ability_demonhunter_shear"),       categories: ["builder"] },
        { id: "dh_sigilofsilence",name: "Sigil of Silence",icon: icon("ability_demonhunter_sigilofsilence"),categories: ["interrupt"] },
        { id: "dh_sigilofflame",name: "Sigil of Flame",   icon: icon("ability_demonhunter_sigilofflame"),categories: ["aoe_dmg"] },
        { id: "dh_sigilofmisery",name: "Sigil of Misery", icon: icon("ability_demonhunter_sigilofmisery"),categories: ["pvp_utility"] },
      ]},
    ],
  },
  {
    id: "evoker",
    name: "Evoker",
    color: "#33937F",
    shared: [
      { id: "evo_quell",          name: "Quell",              icon: icon("ability_evoker_quell"),            categories: ["interrupt"] },
      { id: "evo_obsidscales",    name: "Obsidian Scales",    icon: icon("ability_evoker_obsidianscales"),   categories: ["defensive"] },
      { id: "evo_renewingblaze",  name: "Renewing Blaze",    icon: icon("ability_evoker_renewingblaze"),   categories: ["self_heal"] },
      { id: "evo_hover",          name: "Hover",             icon: icon("ability_evoker_hover"),            categories: ["movement"] },
      { id: "evo_wingbuffet",     name: "Wing Buffet",       icon: icon("ability_evoker_wingbuffet"),       categories: ["utility_2"] },
      { id: "evo_sleepwalk",      name: "Sleep Walk",        icon: icon("ability_evoker_sleepwalk"),        categories: ["cc"] },
      { id: "evo_tailswipe",      name: "Tail Swipe",        icon: icon("ability_evoker_tailswipe"),        categories: ["stun"] },
      { id: "evo_expunge",        name: "Expunge",           icon: icon("ability_evoker_green_01"),         categories: ["dispel"] },
      { id: "evo_zephyr",         name: "Zephyr",            icon: icon("ability_evoker_masterylifebinder_green"), categories: ["raid_cd"] },
      { id: "evo_livingflame",    name: "Living Flame",      icon: icon("ability_evoker_livingflame"),      categories: ["builder"] },
      { id: "evo_azurestrike",   name: "Azure Strike",      icon: icon("ability_evoker_azurestrike"),      categories: ["builder"] },
      { id: "evo_oppressingroar", name: "Oppressing Roar",   icon: icon("ability_evoker_oppressingroar"),   categories: ["pvp_utility"] },
    ],
    specs: [
      { id: "devastation", name: "Devastation", spells: [
        { id: "evo_dragrage",    name: "Dragonrage",       icon: icon("ability_evoker_dragonrage"),       categories: ["major_cd"] },
        { id: "evo_firebreath",  name: "Fire Breath",     icon: icon("ability_evoker_firebreath"),       categories: ["burst_cd", "aoe_dmg"] },
        { id: "evo_disintegrate",name: "Disintegrate",    icon: icon("ability_evoker_disintegrate"),     categories: ["spender"] },
        { id: "evo_pyre",        name: "Pyre",             icon: icon("ability_evoker_pyre"),             categories: ["aoe_dmg"] },
        { id: "evo_etch",        name: "Etch",            icon: icon("ability_evoker_etch"),             categories: ["spender"] },
        { id: "evo_shatteringstar",name: "Shattering Star",icon: icon("ability_evoker_shatteringstar"), categories: ["burst_cd"] },
        { id: "evo_tipthescales",name: "Tip the Scales",  icon: icon("ability_evoker_tipthescales"),     categories: ["burst_cd"] },
        { id: "evo_scorch",      name: "Scorch",          icon: icon("ability_evoker_scorch"),           categories: ["pvp_offensive"] },
      ]},
      { id: "preservation", name: "Preservation", spells: [
        { id: "evo_rewind",   name: "Rewind",             icon: icon("ability_evoker_rewind"),           categories: ["raid_cd"] },
        { id: "evo_stasis",   name: "Stasis",             icon: icon("ability_evoker_stasis"),           categories: ["major_cd"] },
        { id: "evo_emeraldblossom",name: "Emerald Blossom",icon: icon("ability_evoker_emeraldblossom"), categories: ["spender"] },
        { id: "evo_spiritbloom",name: "Spiritbloom",      icon: icon("ability_evoker_spiritbloom"),      categories: ["spender"] },
        { id: "evo_dreambreath",name: "Dream Breath",     icon: icon("ability_evoker_dreambreath"),      categories: ["spender"] },
        { id: "evo_dreamflight",name: "Dream Flight",     icon: icon("ability_evoker_dreamflight"),      categories: ["pvp_defensive"] },
      ]},
      { id: "augmentation", name: "Augmentation", spells: [
        { id: "evo_breathchaos",name: "Breath of Eons",   icon: icon("ability_evoker_breathofeons"),     categories: ["major_cd"] },
        { id: "evo_ebon",       name: "Ebon Might",        icon: icon("ability_evoker_ebonmight"),        categories: ["burst_cd"] },
        { id: "evo_upheaval",   name: "Upheaval",          icon: icon("ability_evoker_upheaval"),         categories: ["spender"] },
        { id: "evo_eruption",   name: "Eruption",          icon: icon("ability_evoker_eruption"),         categories: ["aoe_dmg"] },
        { id: "evo_breathofeons",name: "Breath of Eons",  icon: icon("ability_evoker_breathofeons"),     categories: ["spender"] },
        { id: "evo_blisteringscales",name: "Blistering Scales",icon: icon("ability_evoker_blisteringscales"), categories: ["pvp_offensive"] },
      ]},
    ],
  },
];

export const CLASS_MAP = Object.fromEntries(CLASSES.map((c) => [c.id, c]));

export function getClassSpells(classId: string, specId: string): Spell[] {
  const cls = CLASS_MAP[classId];
  if (!cls) return [];
  const spec = cls.specs.find((s) => s.id === specId);
  return [...cls.shared, ...(spec?.spells ?? [])];
}

export const ICON_BASE = "https://wow.zamimg.com/images/wow/icons/large/";
export const iconUrl = (icon: string) => `${ICON_BASE}${icon}.jpg`;
